#!/usr/bin/env ruby
#
# mongrel Startup script for Mongrel by Tim Morgan
#
# chkconfig: - 85 15
# description: mongrel manages Mongrel
#

app_dir = '/home/inventory/code'

apps = {
  'inventory' => 3000,
  'inventory_test' => 3001
}

if ['stop', 'restart'].include? ARGV.first
  apps.each do |path, port|
    path = File.join app_dir, path
    puts "Stopping #{path}..."
    `mongrel_rails stop -c #{path} -P log/mongrel.pid`
  end
end

if ['start', 'restart'].include? ARGV.first
  apps.each do |path, port|
    path = File.join app_dir, path
    puts "Starting #{path} on #{port}..."
    `mongrel_rails start -d -p #{port} -e production -c #{path} -P log/mongrel.pid`
  end
end

if ['update'].include? ARGV.first
    Dir.chdir("/home/inventory/code/inventory")
    `git pull origin master`

    Dir.chdir("/home/inventory/code/inventory_test")
    `git pull origin master`
end

if ['kill'].include? ARGV.first
    system("kill -9 `ps -ef | grep mongrel_rails | grep -v grep | awk '{print $2}'`")
    system("rm /home/inventory/code/inventory/log/mongrel.pid")
end

unless ['start', 'stop', 'restart', 'update', 'kill'].include? ARGV.first
    puts "Usage: mongrel {start|stop|restart}"
    exit
end

